### ISSUE TITLE
How can i emulate enum

### ISSUE THREAD

**Issue by rogerdielrton** [IndigoUnited/js-dejavu#58]
Example:
var ColorType = dejavu.AbstractClass.declare({
	_id: null,
	_name: null,
	_initialize: function (id, name) {
		this._id = id;
		this._name = name;		
	},
	getName: function() {
		return this._name;
	},	
	$statics: {
	 RED: new ???(51030, "red"),
	 BLUE: new ???(32650, "blue")
	}
});
Please, how can I do it?

**Comment by satazor** [comment]
dejavu has been deprecated and is no longer mantained
